# Generated by Django 5.2.1 on 2025-05-25 08:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='公司名稱')),
                ('address', models.TextField(verbose_name='公司地址')),
                ('geo', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='公司座標')),
                ('address2', models.TextField(blank=True, null=True, verbose_name='公司地址2')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('is_agent', models.BooleanField(default=False, verbose_name='是否代理商')),
                ('tax_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='統一編號')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '客戶資訊',
                'verbose_name_plural': '客戶資訊',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='聯絡人姓名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='聯絡人Email')),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='聯絡人Email2')),
                ('phone', models.CharField(max_length=10, verbose_name='聯絡人電話')),
                ('phone2', models.CharField(blank=True, max_length=10, null=True, verbose_name='聯絡人電話2')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='客戶')),
            ],
            options={
                'verbose_name': '聯絡人資訊',
                'verbose_name_plural': '聯絡人資訊',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, verbose_name='訂單號碼')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='訂單日期')),
                ('order_status', models.CharField(max_length=100, verbose_name='訂單狀態')),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='訂單總金額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='客戶')),
            ],
            options={
                'verbose_name': '訂單紀錄',
                'verbose_name_plural': '訂單紀錄',
            },
        ),
    ]
