# Generated by Django 5.2.1 on 2025-05-25 09:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_total',
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(default=1, max_length=100, verbose_name='訂單地點'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='location_geo',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='訂單地點座標'),
        ),
        migrations.AddField(
            model_name='order',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='machine.machine', verbose_name='機器'),
            preserve_default=False,
        ),
    ]
