# Generated by Django 5.2.1 on 2025-05-25 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='維修/保養項目名稱')),
                ('description', models.TextField(verbose_name='說明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '維修/保養項目',
                'verbose_name_plural': '維修/保養項目',
            },
        ),
        migrations.CreateModel(
            name='Maintain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('maintain_type', models.IntegerField(choices=[(1, '定期保養'), (2, '大保養'), (3, '小保養')], verbose_name='維護類型')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine', verbose_name='機器')),
            ],
            options={
                'verbose_name': '維護紀錄',
                'verbose_name_plural': '維護紀錄',
            },
        ),
        migrations.CreateModel(
            name='MissionMaintain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='維修/保養項目描述')),
                ('status', models.IntegerField(choices=[(1, '未開始'), (2, '進行中'), (3, '已完成')], verbose_name='任務狀態')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='任務開始時間')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='任務結束時間')),
                ('maintain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintain.maintain', verbose_name='維護')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintain.mission', verbose_name='維修/保養項目')),
            ],
            options={
                'verbose_name': '維修/保養任務',
                'verbose_name_plural': '維修/保養任務',
            },
        ),
        migrations.AddField(
            model_name='maintain',
            name='missions',
            field=models.ManyToManyField(through='maintain.MissionMaintain', to='maintain.mission', verbose_name='維修/保養項目'),
        ),
        migrations.AlterUniqueTogether(
            name='maintain',
            unique_together={('machine', 'created_at')},
        ),
    ]
