# Generated by Django 5.2.1 on 2025-05-25 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='電路版編號')),
                ('description', models.TextField(verbose_name='電路描述')),
                ('version', models.CharField(max_length=100, verbose_name='電路版版本')),
                ('color', models.IntegerField(choices=[(1, '紅'), (2, '綠'), (3, '藍'), (4, '黃'), (5, '紫')], verbose_name='電路版顏色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '電路板',
                'verbose_name_plural': '電路板',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CircuitUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('description', models.TextField(verbose_name='電路升級描述')),
                ('file0', models.FileField(upload_to='circuit_upgrade/', verbose_name='電路升級檔案')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.circuit', verbose_name='電路版')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '電路板升級',
                'verbose_name_plural': '電路板升級',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('sn', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='機器序號')),
                ('name', models.CharField(max_length=100, verbose_name='機器名稱')),
                ('description', models.TextField(verbose_name='機器描述')),
                ('typeof', models.IntegerField(choices=[(1, '木頭'), (2, '鋼鐵'), (3, '鋁'), (4, '其他')], verbose_name='機器類型')),
                ('generation', models.IntegerField(verbose_name='機器世代')),
                ('number', models.IntegerField(verbose_name='流水號')),
                ('remote_id', models.CharField(max_length=100, verbose_name='遠端機器序號')),
                ('mac', models.CharField(max_length=100, verbose_name='MAC')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('warranty_start_date', models.DateField(verbose_name='保固開始日期')),
                ('warranty_end_date', models.DateField(verbose_name='保固結束日期')),
                ('warranty_status', models.BooleanField(default=False, verbose_name='保固狀態')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.circuit', verbose_name='電路版')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
            ],
            options={
                'verbose_name': '機器',
                'verbose_name_plural': '機器',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品質測試名稱')),
                ('description', models.TextField(verbose_name='品質測試描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('file0', models.FileField(upload_to='quality_test/', verbose_name='品質測試檔案')),
                ('temp1', models.FloatField(verbose_name='第一溫度')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine', verbose_name='機器')),
            ],
            options={
                'verbose_name': '品質測試',
                'verbose_name_plural': '品質測試',
            },
        ),
        migrations.CreateModel(
            name='TemperatureSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='溫度感測器名稱')),
                ('parameter_file', models.FileField(upload_to='temperature_sensor/', verbose_name='溫度感測器參數檔案')),
                ('description', models.TextField(verbose_name='溫度感測器描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('type', models.IntegerField(choices=[(1, '第一象限'), (2, '風口'), (3, '第三象限'), (4, '第四象限')], verbose_name='溫度感測器類型')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machine', verbose_name='機器')),
            ],
            options={
                'verbose_name': '溫度感測器',
                'verbose_name_plural': '溫度感測器',
                'ordering': ['-created_at'],
            },
        ),
    ]
